retnet:
  _target_: models.RetNetConfig
  max_blocks: 20
  num_layers: 5
  num_heads: 4
  embed_dim: 512
  dropout: 0.1
  blocks_per_chunk: 2
  mask_type: 'autoregressive'
  decay_scale_min_num_blocks: 4
  decay_scale_max_num_blocks: 16
context_length: 1
compute_states_parallel: True
shared_embeddings: False
obs_emb_dim: 256
shared_prediction_token: False
tokenize_actions: True
enable_curiosity: True
